spring.application.name=Mi_cacharrito

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost/mi_cacharrito}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}