spring.application.name=Mi_cacharrito
spring.datasource.url=jdbc:mysql://localhost/mi_cacharrito
spring.datasource.username=root

spring.datasource.password=Lalis2018

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
